name: 67P_Swarm
channels:
  - conda-forge
  - defaults
dependencies:
  - boost-cpp=1.78.0
  - cloudpickle=2.2.0
  - cudatoolkit=9.0
  - ipython=8.7.0
  - loguru=0.5.3
  - matplotlib=3.6.2
  - numpy=1.23.5
  - pandas=1.5.2
  - polyhedral-gravity-model=1.2.1
  - pygmo=2.18.0
  - python=3.8.15
  - pytorch=1.12.1
  - scipy=1.9.3
  - sphinx=5.0.2
  - sphinx_rtd_theme=0.4.3
  - toml=0.10.2
  - tqdm=4.64.1
