name: 67P_Swarm
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pickle
  - math
  - pygmo
  - polyhedral-gravity-model
  - tetgen
  - meshio
  - openmesh
  - pyvista
  - matplotlib.patches
  - matplotlib.pyplot
  - matplotlib
  - pathlib