name: 67P_Swarm
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pygmo
  - polyhedral-gravity-model
  - pyvista
  - matplotlib
  - panel
  - jupyter_backend
  - pykep
  - pyquaternion
  - pip:
      - tetgen
      - desolver