name: 67P_Swarm
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pygmo
  - polyhedral-gravity-model
  - tetgen
  - meshio
  - openmesh-python
  - pyvista
  - matplotlib
  - pip:
      - tetgen
